# Generated by Django 3.1.7 on 2021-03-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postcontain', models.TextField(max_length=400)),
                ('postimage', models.ImageField(upload_to='images/postimage')),
                ('dateofpost', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
