# Generated by Django 3.1.7 on 2021-03-11 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20210311_0953'),
        ('postapp', '0004_auto_20210310_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.userprofile'),
        ),
    ]
