# Generated by Django 3.1.7 on 2021-03-11 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20210311_0953'),
        ('postapp', '0007_auto_20210311_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='account.userprofile'),
            preserve_default=False,
        ),
    ]
