# Generated by Django 3.1.7 on 2021-03-15 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0012_auto_20210315_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='commentreply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='postapp.postcomment'),
        ),
    ]
