# Generated by Django 3.1.7 on 2021-03-15 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0013_postcomment_commentreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='commentdate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
