# Generated by Django 3.1.7 on 2021-03-15 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0014_postcomment_commentdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='commentreply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='postapp.postcomment'),
        ),
    ]
