# Generated by Django 3.1.7 on 2021-03-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0021_post_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='value',
            field=models.CharField(choices=[('LIKE', 'like'), ('UNLIKE', 'unlike')], default='LIKE', max_length=10),
        ),
    ]
