# Generated by Django 3.1.7 on 2021-04-03 13:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('MOB', 'mobile'), ('CL', 'Cloths'), ('EL', 'Electronics'), ('SP', 'Sports'), ('HOAP', 'Home Applications')], max_length=100)),
                ('description', models.TextField(max_length=100)),
                ('image', models.FileField(default='images/productimages/dummy.png', upload_to='images/productimages/')),
                ('price', models.IntegerField(default=0)),
                ('rating', models.ManyToManyField(blank=True, related_name='rating', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
