# Generated by Django 3.1.7 on 2021-04-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210405_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimages',
            name='time_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
