# Generated by Django 3.1.7 on 2021-04-06 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productimages_time_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('mobile', 'MOB'), ('Cloths', 'CL'), ('Electronics', 'EL'), ('Sports', 'SP'), ('Home Applications', 'HOAP')], max_length=100),
        ),
    ]
