# Generated by Django 3.1.7 on 2021-04-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_item',
            field=models.ManyToManyField(blank=True, related_name='cart_item', to='products.Product'),
        ),
    ]
